name = "ModularIndices"
uuid = "96e4cb12-aa16-11e9-3f16-05acf5cf8c1c"
authors = ["Eric P. Hanson"]
version = "0.1.0"

[deps]

[compat]
julia = "1"

[extras]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[targets]
test = ["OffsetArrays", "Test", "StaticArrays"]
